import * as React from 'react'

export type NeevoComponent<Props = any> = React.ComponentType<Props>

export const Button: NeevoComponent
export const Calendar: NeevoComponent
export const Accordion: NeevoComponent
export const AccordionItem: NeevoComponent
export const Card: NeevoComponent
export const CardHeader: NeevoComponent
export const CardBody: NeevoComponent
export const CardFooter: NeevoComponent
export const Checkbox: NeevoComponent
export const Drawer: NeevoComponent
export const DrawerHeader: NeevoComponent
export const DrawerBody: NeevoComponent
export const DrawerSection: NeevoComponent
export const DrawerFooter: NeevoComponent
export const I: NeevoComponent
export const Input: NeevoComponent
export const Page: NeevoComponent
export const PageHeader: NeevoComponent
export const PageBody: NeevoComponent
export const Sidebar: NeevoComponent
export const Content: NeevoComponent
export const Container: NeevoComponent
export const Grid: NeevoComponent
export const Row: NeevoComponent
export const Column: NeevoComponent
export const AppShell: NeevoComponent
export const AppSidebar: NeevoComponent
export const AppSidebarBrand: NeevoComponent
export const AppSidebarNav: NeevoComponent
export const AppSidebarGroup: NeevoComponent
export const AppNavItem: NeevoComponent
export const AppStage: NeevoComponent
export const AppStageHeader: NeevoComponent
export const Modal: NeevoComponent
export const ModalHeader: NeevoComponent
export const ModalBody: NeevoComponent
export const ModalSection: NeevoComponent
export const ModalFooter: NeevoComponent
export const RadioGroup: NeevoComponent
export const RadioOption: NeevoComponent
export const Select: NeevoComponent
export const Options: NeevoComponent
export const Skeleton: NeevoComponent
export const Switch: NeevoComponent
export const Slider: NeevoComponent
export const RangeSlider: NeevoComponent
export const Table: NeevoComponent
export const TableHead: NeevoComponent
export const TableBody: NeevoComponent
export const TableRow: NeevoComponent
export const TableCell: NeevoComponent
export const TableCaption: NeevoComponent
export const TextArea: NeevoComponent
export const Text: NeevoComponent
export const Heading: NeevoComponent
export const ThemeProvider: NeevoComponent
export const Tooltip: NeevoComponent
export const EmptyState: NeevoComponent
export const TagInput: NeevoComponent
export const Popover: NeevoComponent
export const PopoverTrigger: NeevoComponent
export const PopoverContent: NeevoComponent
export const ToastProvider: NeevoComponent
export const ToastViewport: NeevoComponent
export const Toast: NeevoComponent
export function useToast(...args: any[]): any
export const Tabs: NeevoComponent
export const TabsList: NeevoComponent
export const TabsTrigger: NeevoComponent
export const TabsContent: NeevoComponent
export const Pagination: NeevoComponent
export const Timeline: NeevoComponent
export const TimelineItem: NeevoComponent
export const Progress: NeevoComponent
export const CircularProgress: NeevoComponent
export const Breadcrumbs: NeevoComponent
export const Stepper: NeevoComponent
export const Menu: NeevoComponent
export const DropdownMenu: NeevoComponent
export const MenuTrigger: NeevoComponent
export const MenuContent: NeevoComponent
export const MenuItem: NeevoComponent
export const MenuSeparator: NeevoComponent
export const CommandPalette: NeevoComponent
export const Avatar: NeevoComponent
export const Badge: NeevoComponent
export const Divider: NeevoComponent
